before_install:
- sudo apt-get update && sudo apt-get install --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-science texlive-fonts-extra texlive-latex-recommended
  dvipng texlive-lang-cyrillic latex-beamer
script:
- make
- rm -rf */*.pdf
- make
before_deploy:
- mkdir build
- cp */*.pdf build/
deploy:
  provider: releases
  api_key:
    secure: TujEPXvoKN/XeFpkXbLZ6p6ZqTQRO7XIl710gTdgycK8SZGrcmVflZLjalOzdi9PNwueMV86dLJ/0cZNAxuIgjJtFAZ3W6wRkK7BrUTp/CG9thzl/b/ym0gdS96gwJvOwAE+Ca+eoWDFsbsRPYPkGNoGv5rXPCfi48wOQ+Cq2uV5D6yN71t1kUeGy2hGt5/cylA51pxslajdCm2hlYdodYWdrBQ9cycwMj4iooP+Suh/jG9yfXv0igdm7sPOSacILyFLVfpXTa/iqH/fO/OZQI5BrDOnucJcCcjO+lsCftGG49OxTOKSsYAsgKMe0zc43JjMXlSmyhBZr5YiWN5RJ5ieUcnUOkXH3UwXQoEaGLbRE/AClhyBObI7SmczxE4EcZ2vH16QjlGwQkf9wS0AjIGlvhg3nzOYY9wdVensklRP8AtJTrnhW33z96OKwZG/we2jwTxAB2LIlUrTYODsSs13seFDjv13gcXWMNOoWp1tS5aFjG2aEBew/d3ebPHL6kq7D3SW9JURgW4A6sBj+RcFWPbD70TpF9eK0UByAierHD8WIo4DcEhdvG2wmTyGidHheIsNJKoGbU8H5yikdwPyo5bbr8SEkHiuok/nzh/U7TZ9zlMqVv4q/nogZ8awN/jBzoTUPWHIlYsHp2X+d8xX1Lmmj4AzoCyfyB7NSBU=
  file_glob: true
  file: '*/*.pdf'
  on:
    repo: elsys/os-lectures
    tags: true
