
all:


pthread01: pthread01.cc
	g++ -g -Wall -o pthread01 pthread01.cc -lpthread
	
pthread02: pthread02.cc
	g++ -g -Wall -o pthread02 pthread02.cc -lpthread
	
pthread03: pthread03.cc
	g++ -g -Wall -o pthread03 pthread03.cc -lpthread